Refactor product support into testable script

diff --git a/.github/workflows/test-latest-products.yml b/.github/workflows/test-latest-products.yml
--- a/.github/workflows/test-latest-products.yml
+++ b/.github/workflows/test-latest-products.yml
@@ -8,56 +8,73 @@ permissions:
   contents: read
 
 jobs:
-  # test a handful of on-prem tools, they should always pass if they're published
+  load-matrix:
+    runs-on: ubuntu-latest
+    outputs:
+      supported: ${{ steps.load-matrix.outputs.matrix }}
+    steps:
+      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      - name: Load Supported Product Build Matrix
+        id: load-matrix
+        run: echo "matrix=$(tr '\n' ' ' < supported_builds.json | tr -s ' ' )" >> "$GITHUB_OUTPUT"
+
   test-on-prem:
     runs-on: ubuntu-latest
+    needs: ['load-matrix']
     strategy:
       fail-fast: false # run all jobs so we see all failures as soon as possible
       matrix:
-        tool:
-          - consul
-          - nomad
-          - packer
-          - terraform
-          - vault
-        build:
-          - oss
-          - ent
-        exclude:
-          - { tool: packer,    build: ent }
-          - { tool: terraform, build: ent }
-
+        include: ${{ fromJSON( needs.load-matrix.outputs.supported ) }}
     steps:
+      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
       - name: Fetch Tool
         run: |
-          # use hc-releases someday when we have a token for installing it
+          url="https://api.releases.hashicorp.com/v1/releases/${{ matrix.tool }}/latest"
+          echo "::debug::Checking latest version of ${{ matrix.tool }}: $url"
           version="$(
-            curl --fail --silent --show-error "https://api.releases.hashicorp.com/v1/releases/${{ matrix.tool }}/latest" \
+            curl --fail --silent --show-error "$url" \
               | jq --raw-output '.version'
           )"
           if [ -z "$version" ] ; then
-            echo "::error::Failed to fetch latest release of tool ${{ matrix.tool }}" >&2
+            echo "::error Failed to fetch latest release of tool ${{ matrix.tool }}" >&2
             exit 1
           fi
           if [ "${{ matrix.build }}" = "ent" ]; then
             version="${version}+ent"
           fi
           echo "TOOL_VERSION=$version" >> "$GITHUB_ENV"
+          echo "tool version: $version"
 
-          url="$(/usr/bin/printf 'https://releases.hashicorp.com/%s/%s/%s_%s_linux_amd64.zip' \
-            "${{ matrix.tool }}" "$version" "${{ matrix.tool }}" "$version"
+          host_os="$(uname -s)"
+          host_os="${host_os,,}"
+          host_arch="$(uname -m)"
+          host_arch="${host_arch,,}"
+          if [ "$host_arch" = 'x86_64' ]; then host_arch=amd64 ; fi
+
+          blob="$(curl --fail --silent --show-error "https://api.releases.hashicorp.com/v1/releases/${{ matrix.tool }}/${version}")"
+          url="$(jq --raw-output --arg os "$host_os" --arg arch "$host_arch" '
+                .builds[]
+                | select( .os == $os and .arch == $arch )
+                | .url
+              ' <<< "$blob"
           )"
-          echo "Fetching tool $url"
-          cd "${{ runner.temp }}"
-          curl --fail --silent --show-error -o "${{ matrix.tool }}.zip" "$url"
-          unzip "${{ matrix.tool }}.zip"
-          /bin/ls -l "${{ matrix.tool }}"
-          file "${{ matrix.tool }}"
-          uname -a
-          "./${{ matrix.tool }}" version
+
+          echo "Fetching tool from [$url]"
+          (
+            cd "${{ runner.temp }}"
+            curl --fail --silent --show-error -o "./${{ matrix.tool }}.zip" "$url"
+            unzip -o "${{ matrix.tool }}.zip"
+          )
 
       - name: Test Tool
         uses: hashicorp/actions-validate-product-version@v1
         with:
           expected_version: ${{ env.TOOL_VERSION }}
           artifact_path: ${{ runner.temp }}/${{ matrix.tool }}
+
+      # use latest local commit; useful in local testing
+      #- uses: ./
+      #  with:
+      #    expected_version: ${{ env.TOOL_VERSION }}
+      #    artifact_path: ${{ runner.temp }}/${{ matrix.tool }}.zip
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,13 +32,22 @@ jobs:
       - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
 
       - name: Run Test Suite
-        run: bats ./tests/test-versions.bats
+        run: bats --recursive ./tests/
 
   test-relative:
     runs-on: ubuntu-latest
     needs: [ 'test-suite' ]
     steps:
       - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+
+      # include the test tool in the supported builds data.
+      # filter through jq to validate JSON before writing the file.
+      - name: Support Test Tool
+        run: |
+          echo '[{"build":"oss","tool":"test_tool_plain_executable"}]' \
+            | jq --compact-output \
+            | tee ./supported_builds.json
+
       # Test with relative path
       - name: Run Action (relative path)
         uses: hashicorp/actions-validate-product-version@v1
@@ -52,6 +61,15 @@ jobs:
     needs: [ 'test-suite' ]
     steps:
       - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+
+      # include the test tool in the supported builds data.
+      # filter through jq to validate JSON before writing the file.
+      - name: Support Test Tool
+        run: |
+          echo '[{"build":"oss","tool":"test_tool_plain_executable"}]' \
+            | jq --compact-output \
+            | tee ./supported_builds.json
+
       # Test with absolute path
       - name: Copy Test Tool to Absolute Path
         id: copy_tool
@@ -63,3 +81,41 @@ jobs:
           expected_version: '1.2.3'
           # this path is relative to the action path
           artifact_path: ${{ runner.temp }}/test_tool_plain_executable
+
+  # test against something on the releases site that is not expected to ever pass.
+  # terraform-provider-fastly is chosen arbitrarily within this category.
+  test-unsupported-product:
+    runs-on: ubuntu-latest
+    needs: [ 'test-suite' ]
+    env:
+      PRODUCT: terraform-provider-fastly
+    steps:
+      - name: Check latest tool version
+        run: |
+          url="https://api.releases.hashicorp.com/v1/releases/${{ env.PRODUCT }}/latest"
+          echo "::debug::Checking latest version of ${PRODUCT}: $url"
+          version="$(
+            curl --fail --silent --show-error "$url" \
+              | jq --raw-output '.version'
+          )"
+          if [ -z "$version" ] ; then
+            echo "::error Failed to fetch latest release of tool [$PRODUCT]" >&2
+            exit 1
+          fi
+          echo "EXP_VERSION=${version}" >> "$GITHUB_ENV"
+
+      - name: Run Action (expected to fail)
+        id: test-version
+        continue-on-error: true
+        uses: hashicorp/actions-validate-product-version@v1
+        with:
+          expected_version: ${{ env.EXP_VERSION }}
+          # the action should fail before executing the artifact
+          artifact_path: /bin/false
+
+      - name: Check Result
+        if: contains(fromJSON('["success", "failure"]'), steps.test-version.outcome)
+        run: |
+          # invert error from previous step (expected to fail)
+          echo "::debug::result: [${{ steps.test-version.outcome }}]"
+          [ "${{ steps.test-version.outcome }}" = 'failure' ]
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -13,21 +13,39 @@ inputs:
 runs:
   using: "composite"
   steps:
-    # This assumes that each tool can be run as `$tool version` ("version" is a sub-command).
-    - name: Check artifacts
+
+    - name: Check Product Support
+      id: check-product-support
+      shell: bash
+      run: |
+        tool="${{ inputs.artifact_path }}"
+        tool="${tool##*/}"
+        supported="$(${{ github.action_path }}/check-product-support "${{ inputs.artifact_path }}")"
+        echo "supported=$supported" > "$GITHUB_OUTPUT"
+        echo "::debug::output: $supported"
+
+        if [ "$supported" != 'true' ] ; then
+          echo "::error ${tool} is not supported by this action." 1>&2
+          exit 1
+        fi
+
+    - name: Check Artifact
+      if: steps.check-product-support.outputs.supported == 'true'
       shell: bash
       env:
         TEST_DIR: "${{ runner.temp }}/validate-product-version"
         EXP_VERSION: "${{ inputs.expected_version }}"
       run: |
+        echo "::debug::testing ${{ inputs.artifact_path }} version"
         case "${{ inputs.artifact_path }}" in
           /*) ARTIFACT="${{ inputs.artifact_path }}" ;; # absolute path used as-is
           *)  ARTIFACT="$(pwd -P)/${{ inputs.artifact_path }}" ;;
         esac
         export ARTIFACT
+        echo "::debug::ARTIFACT=$ARTIFACT"
 
         if ! [ -e "$ARTIFACT" ]; then
-          echo "::error::$ARTIFACT: artifact path does not exist" 1>&2
+          echo "::error $ARTIFACT: artifact path does not exist" 1>&2
           exit 1
         fi
 
